export const catalog = [
  { id: '01', name: 'The Editorial', group: 'Editorial', mood: 'Warm · considered · confident', description: 'A magazine-like introduction, expressive serif typography, and a beautifully ordered research index.', colors: ['#f6f1e8', '#962c32', '#242321'], recommended: true },
  { id: '02', name: 'Swiss Index', group: 'Structured', mood: 'Precise · graphic · direct', description: 'A strong typographic grid with cobalt accents. Clear hierarchy puts your work front and center.', colors: ['#f7f7f2', '#234cdd', '#18191c'] },
  { id: '03', name: 'Quiet Scholar', group: 'Minimal', mood: 'Literary · calm · timeless', description: 'A personal reading room: a persistent identity column, generous margins, and a refined paper list.', colors: ['#faf8f2', '#344c3d', '#bab9a8'], recommended: true },
  { id: '04', name: 'Night Signal', group: 'Expressive', mood: 'Immersive · technical · sharp', description: 'A deep navy canvas with luminous diagrams and modern typography for an AI research identity.', colors: ['#101925', '#7ae0d0', '#a9b7d1'] },
  { id: '05', name: 'Soft Geometry', group: 'Expressive', mood: 'Open · warm · approachable', description: 'An asymmetrical collection of soft cards, pastel surfaces, and small moments of personality.', colors: ['#fbf8f2', '#ebad91', '#b9c8ad'] },
  { id: '06', name: 'Field Notes', group: 'Editorial', mood: 'Thoughtful · tactile · personal', description: 'Notebook-inspired margins and research notes make the page feel like an evolving body of work.', colors: ['#f4f1e6', '#65775b', '#d9b26d'] },
  { id: '07', name: 'Gallery of Ideas', group: 'Editorial', mood: 'Visual · spacious · curated', description: 'Paper figures become the focal point in a generous, image-led portfolio of research projects.', colors: ['#f4f1eb', '#242321', '#b4a99b'], recommended: true },
  { id: '08', name: 'Research Atlas', group: 'Structured', mood: 'Connected · systematic · clear', description: 'A navigable research map, precise information panels, and an organized publication timeline.', colors: ['#f5f8fb', '#315fc0', '#a8c2df'] },
  { id: '09', name: 'Monochrome Studio', group: 'Minimal', mood: 'Bold · distilled · memorable', description: 'Oversized typography and architectural black-and-white contrast give your name a distinct presence.', colors: ['#fafaf7', '#141414', '#b6b6b0'] },
  { id: '10', name: 'Open Horizon', group: 'Expressive', mood: 'Airy · optimistic · expansive', description: 'A panoramic blue hero, an abstract horizon, and open research cards with a contemporary academic feel.', colors: ['#e7f0f8', '#295277', '#d5dfb9'] },
  { id: '11', name: 'Oxford Blue', collection: 'refinements', module: 'refined-a', group: 'Editorial', mood: 'Navy · cool white · editorial', description: 'The presence of 01, the reading space of 03, and the illustrated research of 07. A full introduction beside a compact academic profile.', colors: ['#f8fafc', '#173b65', '#899aab'], recommended: true },
  { id: '12', name: 'Graphite Journal', collection: 'refinements', module: 'refined-a', group: 'Sidebar', mood: 'White · graphite · restrained', description: 'A persistent identity column and a generous reading column. Real paper figures give the monochrome publication list texture.', colors: ['#ffffff', '#252a30', '#a7aeb5'], recommended: true },
  { id: '13', name: 'Tidal Notes', collection: 'refinements', module: 'refined-b', group: 'Editorial', mood: 'White · deep teal · open', description: 'A crisp editorial masthead, quiet margin notes, and an offset gallery. A little color in the details, plenty of room for your words.', colors: ['#f7fbfc', '#126b72', '#b1cccf'] },
  { id: '14', name: 'Indigo Folio', collection: 'refinements', module: 'refined-b', group: 'Sidebar', mood: 'Indigo · cool mist · literary', description: 'A journal-like reading column, a small academic navigation rail, and image-and-text paper spreads with restrained indigo accents.', colors: ['#f6f7ff', '#4a4ba1', '#c3c6dd'] },
  { id: '15', name: 'Silver Archive', collection: 'refinements', module: 'refined-c', group: 'Editorial', mood: 'White · slate · precise', description: 'A serif masthead and a complete academic introduction, followed by spacious horizontal publication rows with generous paper figures.', colors: ['#ffffff', '#313c47', '#d9dee3'] },
  { id: '16', name: 'Ink & Paper', collection: 'refinements', module: 'refined-c', group: 'Sidebar', mood: 'Ink navy · white · composed', description: 'An ink-colored identity panel anchors a bright reading space. Your full introduction leads into an illustrated research gallery.', colors: ['#192b3c', '#ffffff', '#c9d6df'] },
  { id: '17', name: 'Cobalt Grid', collection: 'bold', module: 'bold-a', group: 'Light', mood: 'Cobalt · graphic · confident', description: 'Oversized modern typography, a graphic opening, and large research cards. An open, horizontal layout with your complete introduction.', colors: ['#ffffff', '#1846ef', '#161b27'], recommended: true },
  { id: '18', name: 'After Hours', collection: 'bold', module: 'bold-a', group: 'Dark', mood: 'Midnight · silver · atmospheric', description: 'A dramatic dark canvas, orbital line work, and luminous paper figures. A full-width masthead gives way to a focused reading space.', colors: ['#0b1220', '#b6e9f2', '#f0f4fa'] },
  { id: '19', name: 'Research Exhibition', collection: 'bold', module: 'bold-b', group: 'Light', mood: 'White · violet · sculptural', description: 'An expressive exhibition-style identity and an asymmetric research gallery. Big shifts in scale make the page feel more alive.', colors: ['#fafaff', '#5c3cf0', '#161421'], recommended: true },
  { id: '20', name: 'Open Circuit', collection: 'bold', module: 'bold-c', group: 'Light', mood: 'Mint · ink · expansive', description: 'A panoramic mint opening, a complete introduction arranged across the page, and an expansive gallery of research figures.', colors: ['#c8f2df', '#172e29', '#ffffff'] },
  { id: '21', name: 'Contour', collection: 'elegant', module: 'elegant-a', group: 'Violet', mood: 'Quiet · intricate · connected', description: 'The selected sculpted nebula: a dense, interactive particle cloud, a complete introduction, and research figures that dissolve and reassemble.', colors: ['#fafaff', '#66578c', '#262430'], recommended: true },
  { id: '22', name: 'Jade Pavilion', collection: 'elegant', module: 'elegant-b', group: 'Jade', mood: 'Jade · white · sculptural', description: 'The openness of 20 in a softer jade palette. A sculptural centerpiece, airy serif type, and spacious research spreads.', colors: ['#e7f2ec', '#315949', '#ffffff'], recommended: true },
  { id: '23', name: 'Lattice', collection: 'elegant', module: 'elegant-c', group: 'Silver', mood: 'Silver · ink · iridescent', description: 'An abstract folded surface in pale violet and mint, a distinctive typographic identity, and precise illustrated publication rows.', colors: ['#f6f8fb', '#243344', '#ced8eb'] },
  { id: '24', name: 'Two highlights + index', collection: 'research', module: 'research', focus: '#ct-research', group: 'Figures', mood: 'Two figures · compact supporting list', description: 'Give two papers a generous visual introduction, then keep the remaining work easy to scan. My preferred balance for your homepage.', colors: ['#ffffff', '#75618d', '#ded7e9'], recommended: true },
  { id: '25', name: 'Editorial spreads', collection: 'research', module: 'research', focus: '#ct-research', group: 'Figures', mood: 'Four large figures · illustrated rows', description: 'Give every paper an equally generous figure beside its title, authors, and summary. Best when the diagrams need room.', colors: ['#ffffff', '#75618d', '#ded7e9'] },
  { id: '26', name: 'Figure gallery', collection: 'research', module: 'research', focus: '#ct-research', group: 'Figures', mood: 'Four figures · a balanced 2 × 2 gallery', description: 'A visual overview with consistent cards and prominent publication titles. The closest continuation of the gallery in design 21.', colors: ['#ffffff', '#75618d', '#ded7e9'] },
  { id: '27', name: 'Typographic journal', collection: 'research', module: 'research', focus: '#ct-research', group: 'Text', mood: 'No figures · typography and summaries', description: 'A pure reading experience. Strong titles, full authors, and concise summaries carry the section without paper figures.', colors: ['#ffffff', '#75618d', '#ded7e9'] },
  { id: '28', name: 'Expandable figures', collection: 'research', module: 'research', focus: '#ct-research', group: 'Figures', mood: 'Compact list · figures on demand', description: 'Keep the publication list concise and open a figure with its summary when you want a closer look. The first paper starts expanded.', colors: ['#ffffff', '#75618d', '#ded7e9'] },
];

const storageKey = 'xiuyuz-design-shortlist';
export function getFavorites() {
  try { const value = JSON.parse(localStorage.getItem(storageKey) || '[]'); return Array.isArray(value) ? value.filter(id => catalog.some(c => c.id === id)) : []; }
  catch { return []; }
}
export function toggleFavorite(id) {
  const current = getFavorites();
  const next = current.includes(id) ? current.filter(x => x !== id) : [...current, id];
  try { localStorage.setItem(storageKey, JSON.stringify(next)); } catch {}
  return next;
}
