import { data } from './data.js';
import { catalog } from './catalog.js';
const requested = new URLSearchParams(location.search).get('design');
const id = catalog.some(c => c.id === requested) ? requested : '01';
const group = catalog.find(c => c.id === id).module || (Number(id) <= 3 ? 'editorial' : Number(id) <= 6 ? 'expressive' : Number(id) <= 9 ? 'structural' : 'horizon');
const stylesheet = document.createElement('link');
stylesheet.rel = 'stylesheet';
stylesheet.href = `./concepts/${group}.css`;
const styleReady = new Promise((resolve, reject) => { stylesheet.onload = resolve; stylesheet.onerror = reject; });
document.head.append(stylesheet);
const [{ concepts }] = await Promise.all([import(`./concepts/${group}.js?v=dark-assets-8`), styleReady]);
document.title = `${data.name} — ${catalog.find(c => c.id === id).name}`;
document.querySelector('#design-root').innerHTML = concepts[id].render(data);
await concepts[id].mount?.(document.querySelector('#design-root'));
document.documentElement.dataset.design = id;
await document.fonts.ready;
if (location.hash) document.getElementById(location.hash.slice(1))?.scrollIntoView({behavior: 'instant'});
window.designReady = true;
