const e = (value = '') => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const external = 'target="_blank" rel="noopener noreferrer"';
const authors = paper => e(paper.authors).replaceAll('XiuYu Zhang', '<strong>XiuYu Zhang</strong>');

function field() {
  return `<svg class="rx-field" viewBox="0 0 1100 340" aria-hidden="true" focusable="false"><defs><pattern id="rx-dots" width="22" height="22" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="currentColor" opacity=".17"/></pattern></defs><rect width="1100" height="340" fill="url(#rx-dots)"/><g class="rx-orbit" transform="translate(788 170) rotate(-24)">${Array.from({length: 17}, (_, i) => `<ellipse cx="0" cy="0" rx="${45 + i * 8.8}" ry="${138 - i * 5.5}" fill="none" stroke="currentColor" stroke-width="1.6"/>`).join('')}</g><g fill="currentColor"><path d="M468 63h18v-18h5v18h18v5h-18v18h-5V68h-18z"/><path d="M1031 262h18v-18h5v18h18v5h-18v18h-5v-18h-18z"/><circle cx="978" cy="66" r="5"/><circle cx="555" cy="276" r="3"/></g><path d="M476 65L978 66 1050 264 555 276Z" fill="none" stroke="currentColor" opacity=".23" stroke-dasharray="3 7"/></svg>`;
}

function paperCard(paper, index) {
  return `<article class="rx-paper ${index === 0 ? 'rx-featured' : ''}"><a class="rx-paper-image" href="${e(paper.url)}" ${external} aria-label="Read ${e(paper.title)}"><img src="${e(paper.image)}" alt="Research figure from ${e(paper.title)}" loading="lazy"><span class="rx-image-arrow" aria-hidden="true">↗</span></a><div class="rx-paper-copy"><div class="rx-paper-meta"><span>${String(index + 1).padStart(2, '0')} / ${e(paper.tag)}</span><span>${e(paper.year)}</span></div><h3><a href="${e(paper.url)}" ${external}>${e(paper.title)}</a></h3><p class="rx-authors">${authors(paper)}</p>${index === 0 ? `<p class="rx-summary">${e(paper.summary)}</p>` : ''}<div class="rx-paper-links"><a href="${e(paper.url)}" ${external}>Read paper <span aria-hidden="true">↗</span></a>${paper.code ? `<a href="${e(paper.code)}" ${external}>Code <span aria-hidden="true">↗</span></a>` : ''}</div></div></article>`;
}

function render(data) {
  return `<div class="concept concept-19" id="rx-top"><div class="rx-wrap"><header class="rx-header"><a class="rx-logo" href="#rx-top" aria-label="XiuYu Zhang, home">xz<span>✳</span></a><nav aria-label="Page navigation"><a href="#rx-about">About</a><a href="#rx-research">Research</a><a href="mailto:${e(data.email)}">Get in touch ↗</a></nav></header><div><section class="rx-hero" aria-labelledby="rx-name"><div class="rx-hero-meta"><span>COMPUTER SCIENCE · NATIONAL UNIVERSITY OF SINGAPORE</span><span>RESEARCH / PERSONAL WEBSITE</span></div><h1 id="rx-name"><span>XiuYu</span> <em>Zhang.</em></h1><div class="rx-hero-field">${field()}<p>Reasoning.<br>Representation.<br><em>Reliable AI.</em></p><span class="rx-field-label">IDEAS ACROSS LANGUAGE & VISION</span></div><div class="rx-hero-foot"><span>Ph.D. student · Singapore</span><a href="#rx-about">Meet the researcher <span aria-hidden="true">↓</span></a><div><a href="${e(data.scholarUrl)}" ${external}>Scholar ↗</a><a href="${e(data.githubUrl)}" ${external}>GitHub ↗</a></div></div></section><section class="rx-about" id="rx-about"><div class="rx-section-heading"><span class="rx-section-number">01 / INTRODUCTION</span><h2>Intelligence, with<br><em>understanding.</em></h2></div><div class="rx-introduction full-introduction">${data.introductionHtml}</div></section><section class="rx-research" id="rx-research"><div class="rx-section-heading rx-research-heading"><div><span class="rx-section-number">02 / SELECTED WORK</span><h2>From questions<br><em>to research.</em></h2></div><a class="rx-text-link" href="${e(data.scholarUrl)}" ${external}>All publications <span aria-hidden="true">↗</span></a></div><div class="rx-papers">${data.papers.slice(0, 4).map(paperCard).join('')}</div></section><section class="rx-education" id="rx-education"><div class="rx-education-heading"><span class="rx-section-number">03 / EDUCATION</span><h2>A continuing <em>curiosity.</em></h2></div><div class="rx-schools">${data.education.map(item => `<article><span>${e(item.years)}</span><h3>${e(item.school)}</h3><p>${e(item.degree)}</p></article>`).join('')}</div></section><section class="rx-contact"><span class="rx-section-number">LET’S CONNECT</span><div><h2>Good questions<br>start <em>conversations.</em></h2><a href="mailto:${e(data.email)}" aria-label="Email ${e(data.email)}"><span aria-hidden="true">↗</span></a></div><a class="rx-email" href="mailto:${e(data.email)}">${e(data.email)}</a></section></div><footer class="rx-footer"><span>© ${e(data.name)} · Singapore</span><a href="#rx-top">Back to top ↑</a></footer></div></div>`;
}

export const concepts = { '19': { render } };
