const escape = (value = '') => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(data) {
  return `<div class="concept concept-10">
    <div class="hz-sky"><header class="hz-nav"><a class="hz-mark" href="#hz-home">xy<span>↗</span></a><nav aria-label="Page navigation"><a href="#hz-research">Research</a><a href="#hz-about">About</a><a href="mailto:${escape(data.email)}">Say hello ↗</a></nav></header>
    <section class="hz-hero" id="hz-home"><div class="hz-hero-copy"><p class="hz-kicker">A RESEARCHER IN PURSUIT OF UNDERSTANDING</p><h1>XiuYu<br><em>Zhang.</em></h1><p class="hz-role">${escape(data.role)}<br>${escape(data.institution)}</p><a class="hz-hero-link" href="#hz-research">Discover the research <span>↓</span></a></div><div class="hz-orbit" aria-hidden="true"><svg viewBox="0 0 520 500" fill="none"><defs><linearGradient id="hz-gradient" x1="100" y1="0" x2="400" y2="500" gradientUnits="userSpaceOnUse"><stop stop-color="#f8fcff"/><stop offset="1" stop-color="#9dbad1"/></linearGradient></defs><circle cx="260" cy="250" r="176" fill="url(#hz-gradient)" opacity=".8"/><g stroke="#6a91b2" stroke-width=".6"><ellipse cx="260" cy="250" rx="236" ry="78" transform="rotate(-28 260 250)"/><ellipse cx="260" cy="250" rx="202" ry="118" transform="rotate(-28 260 250)"/><ellipse cx="260" cy="250" rx="175" ry="175"/><ellipse cx="260" cy="250" rx="104" ry="175" transform="rotate(-28 260 250)"/><ellipse cx="260" cy="250" rx="41" ry="175" transform="rotate(-28 260 250)"/><path d="M90 296L430 204M110 349L406 153M86 240L430 260"/></g><circle cx="459" cy="164" r="7" fill="#295577"/><circle cx="146" cy="98" r="5" fill="#fcfcf6"/><circle cx="307" cy="412" r="5" fill="#c3d09e"/></svg><span class="hz-orbit-note">REPRESENTATION → REASONING → TRUST</span></div><div class="hz-bottom"><span>COMPUTER SCIENCE / NUS</span><p>Intelligence,<br><em>with intention.</em></p><span>SINGAPORE · 01° N</span></div></section></div>
    <section class="hz-intro" id="hz-about"><p class="hz-label">THE QUESTIONS THAT DRIVE ME</p><div><h2>How do we build AI<br>we can <em>understand and trust?</em></h2><p>${escape(data.bio)}</p><div class="hz-topics">${data.interests.map((t,i)=>`<span><small>0${i+1}</small>${escape(t)}</span>`).join('')}</div></div></section>
    <section class="hz-research" id="hz-research"><div class="hz-section-head"><div><p class="hz-label">IDEAS IN PRACTICE</p><h2>Research, <em>in focus.</em></h2></div><a href="${escape(data.scholarUrl)}" target="_blank" rel="noopener">All publications ↗</a></div><div class="hz-projects">${data.papers.slice(0,4).map((p,i)=>`<article class="hz-paper"><a class="hz-paper-image hz-paper-image-${i}" href="${escape(p.url)}" target="_blank" rel="noopener"><img src="${escape(p.image)}" alt="${escape(p.title)} — research figure"><span>0${i+1} /</span><b aria-hidden="true">↗</b></a><div class="hz-paper-info"><p class="hz-paper-meta"><span>${escape(p.tag)}</span><span>${escape(p.year)}</span></p><h3><a href="${escape(p.url)}" target="_blank" rel="noopener">${escape(p.title)}</a></h3><p class="hz-authors">${escape(p.authors)}</p></div></article>`).join('')}</div></section>
    <section class="hz-path"><div><p class="hz-label">ALONG THE WAY</p><h2>Places that<br>shaped my <em>perspective.</em></h2></div><div class="hz-education">${data.education.map(e=>`<article><span>${escape(e.years)}</span><h3>${escape(e.school)}</h3><p>${escape(e.degree)}</p></article>`).join('')}</div></section>
    <footer class="hz-footer"><div><p class="hz-label">THE NEXT CONVERSATION</p><h2>Ideas travel further<br><em>together.</em></h2><a class="hz-contact" href="mailto:${escape(data.email)}">${escape(data.email)} ↗</a></div><nav aria-label="Profile links"><a href="${escape(data.scholarUrl)}" target="_blank" rel="noopener">Google Scholar ↗</a><a href="${escape(data.githubUrl)}" target="_blank" rel="noopener">GitHub ↗</a><a href="#hz-home">Back to the horizon ↑</a></nav><div class="hz-signoff"><span>${escape(data.name)}</span><span>${escape(data.lab)} · Singapore</span></div></footer>
  </div>`;
}
export const concepts = { '10': { render } };
