const e = (value = '') => String(value).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const links = (items) => items.map(item => `<a href="${e(item.url)}" target="_blank" rel="noopener noreferrer">${e(item.name)} <span aria-hidden="true">↗</span></a>`).join('');
const authors = p => e(p.authors).replaceAll('XiuYu Zhang', '<strong>XiuYu Zhang</strong>');
const schools = (data, prefix) => data.education.map(item => `<article class="${prefix}-school"><span>${e(item.years)}</span><h3>${e(item.school)}</h3><p>${e(item.degree)}</p></article>`).join('');
const paperImage = p => `<img src="${e(p.image)}" alt="Research figure from ${e(p.title)}" loading="lazy">`;

function silver(data) {
  return `<div class="concept concept-15"><div class="sa-wrap">
    <header class="sa-header"><a href="#sa-top" class="sa-mark">XZ / ACADEMIC PROFILE</a><nav aria-label="Page navigation"><a href="#sa-about">About</a><a href="#sa-work">Research</a><a href="mailto:${e(data.email)}">Contact ↗</a></nav></header>
    <section class="sa-title" id="sa-top"><div><span class="sa-eyebrow">COMPUTER SCIENCE · SINGAPORE</span><h1>XiuYu <em>Zhang.</em></h1></div><div class="sa-position"><p>${e(data.role)}</p><span>${e(data.institution)}</span><a href="${e(data.scholarUrl)}" target="_blank" rel="noopener">Google Scholar ↗</a></div></section>
    <section class="sa-about" id="sa-about"><aside class="sa-margin"><h2>About me</h2><div class="sa-affiliation"><span>RESEARCH GROUPS</span>${links(data.groups)}</div><div class="sa-affiliation"><span>CO-ADVISORS</span>${links(data.advisors)}</div><div class="sa-affiliation"><span>ELSEWHERE</span><a href="${e(data.githubUrl)}" target="_blank" rel="noopener">GitHub ↗</a><a href="mailto:${e(data.email)}">${e(data.email)} ↗</a></div></aside><div class="sa-introduction full-introduction">${data.introductionHtml}</div></section>
    <section class="sa-research" id="sa-work"><div class="sa-section-head"><h2>Selected <em>research.</em></h2><span>PUBLICATIONS & PREPRINTS / 2026</span></div><div class="sa-paper-list">${data.papers.slice(0,4).map((p,i)=>`<article class="sa-paper"><span class="sa-number">${String(i+1).padStart(2,'0')}</span><a class="sa-paper-figure" href="${e(p.url)}" target="_blank" rel="noopener" aria-label="Read ${e(p.title)}">${paperImage(p)}</a><div class="sa-paper-body"><p class="sa-meta"><span>${e(p.tag)}</span><span>${e(p.year)}</span></p><h3><a href="${e(p.url)}" target="_blank" rel="noopener">${e(p.title)}</a></h3><p class="sa-authors">${authors(p)}</p><p class="sa-summary">${e(p.summary)}</p><div class="sa-paper-links"><a href="${e(p.url)}" target="_blank" rel="noopener">Read paper ↗</a>${p.code?`<a href="${e(p.code)}" target="_blank" rel="noopener">Code ↗</a>`:''}</div></div></article>`).join('')}</div><a class="sa-all" href="${e(data.scholarUrl)}" target="_blank" rel="noopener">Complete publication list on Google Scholar <span>↗</span></a></section>
    <section class="sa-education"><div class="sa-section-head"><h2>Academic <em>path.</em></h2><span>EDUCATION</span></div><div class="sa-schools">${schools(data,'sa')}</div></section>
    <footer class="sa-footer"><a href="mailto:${e(data.email)}">${e(data.email)} ↗</a><span>${e(data.name)} · ${e(data.institution)}</span><a href="#sa-top">Back to top ↑</a></footer>
  </div></div>`;
}

function ink(data) {
  return `<div class="concept concept-16"><div class="ip-layout"><aside class="ip-panel"><div class="ip-panel-top"><a href="#ip-top" class="ip-monogram" aria-label="XiuYu Zhang">xz.</a><span>SINGAPORE / NUS</span></div><h1>XiuYu<br> <em>Zhang.</em></h1><p class="ip-role">${e(data.role)}</p><p class="ip-university">${e(data.institution)}</p><nav class="ip-sections" aria-label="Page navigation"><a href="#ip-about"><span>01</span>Introduction</a><a href="#ip-research"><span>02</span>Research</a><a href="#ip-education"><span>03</span>Education</a></nav><div class="ip-network"><span class="ip-label">RESEARCH GROUPS</span>${links(data.groups)}</div><div class="ip-network"><span class="ip-label">CO-ADVISORS</span>${links(data.advisors)}</div><div class="ip-contact"><a href="${e(data.scholarUrl)}" target="_blank" rel="noopener">Scholar ↗</a><a href="${e(data.githubUrl)}" target="_blank" rel="noopener">GitHub ↗</a><a href="mailto:${e(data.email)}">Email ↗</a></div></aside>
    <div class="ip-content" id="ip-top"><header class="ip-topline"><span>RESEARCH & ACADEMIC PROFILE</span><a href="mailto:${e(data.email)}">${e(data.email)} ↗</a></header><section class="ip-about" id="ip-about"><div class="ip-section-title"><span>01 /</span><h2>A little about me.</h2></div><div class="ip-introduction full-introduction">${data.introductionHtml}</div></section>
    <section class="ip-research" id="ip-research"><div class="ip-section-title"><span>02 /</span><h2>Selected research.</h2></div><div class="ip-papers">${data.papers.slice(0,4).map((p,i)=>`<article class="ip-paper"><a class="ip-figure" href="${e(p.url)}" target="_blank" rel="noopener" aria-label="Read ${e(p.title)}">${paperImage(p)}<span aria-hidden="true">↗</span></a><p class="ip-meta"><span>${e(p.tag)}</span><span>${e(p.year)}</span></p><h3><a href="${e(p.url)}" target="_blank" rel="noopener">${e(p.title)}</a></h3><p class="ip-authors">${authors(p)}</p><div class="ip-paper-links"><a href="${e(p.url)}" target="_blank" rel="noopener">Paper ↗</a>${p.code?`<a href="${e(p.code)}" target="_blank" rel="noopener">Code ↗</a>`:''}</div></article>`).join('')}</div><a class="ip-all" href="${e(data.scholarUrl)}" target="_blank" rel="noopener">See all publications on Google Scholar <span>↗</span></a></section>
    <section class="ip-education" id="ip-education"><div class="ip-section-title"><span>03 /</span><h2>Education.</h2></div><div class="ip-schools">${schools(data,'ip')}</div></section><footer class="ip-footer"><span>${e(data.name)} · ${e(data.lab)}</span><a href="#ip-top">Back to top ↑</a></footer>
    </div></div></div>`;
}
export const concepts = { '15': { render: silver }, '16': { render: ink } };
