const esc = (value = '') => String(value).replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
const arrow = '<span aria-hidden="true">↗</span>';
const link = (url, text, className = '') => `<a class="${className}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${text}</a>`;
const profiles = data => `${link(data.scholarUrl, `Google Scholar ${arrow}`)}${link(data.githubUrl, `GitHub ${arrow}`)}<a href="mailto:${esc(data.email)}">Email ${arrow}</a>`;
const paperLinks = paper => `${link(paper.url, `Read paper ${arrow}`)}${paper.code ? link(paper.code, `Code ${arrow}`) : ''}`;
const papers = data => data.papers.filter(paper => paper.image).slice(0, 4);
const figure = paper => `<img src="${esc(paper.image)}" alt="Research figure from ${esc(paper.title)}" loading="lazy">`;
const motif = (type) => type === 0 ? '<svg viewBox="0 0 120 82" fill="none" aria-hidden="true"><path d="M20 20H80V70H20zM40 10H100V60H40z" stroke="currentColor" stroke-width="2"/><path d="M20 20L40 10M80 20L100 10M80 70L100 60M20 70L40 60" stroke="currentColor" stroke-width="2"/></svg>' : type === 1 ? '<svg viewBox="0 0 120 82" fill="none" aria-hidden="true"><path d="M8 42H40L65 16H105M40 42L65 68H105" stroke="currentColor" stroke-width="2"/><circle cx="40" cy="42" r="6" fill="currentColor"/><circle cx="105" cy="16" r="6" fill="currentColor"/><circle cx="105" cy="68" r="6" fill="currentColor"/></svg>' : '<svg viewBox="0 0 120 82" fill="none" aria-hidden="true"><circle cx="60" cy="41" r="31" stroke="currentColor" stroke-width="2"/><circle cx="60" cy="41" r="22" stroke="currentColor" stroke-width="1"/><path d="M48 42L56 50L73 32" stroke="currentColor" stroke-width="3"/></svg>';

function cobalt(data) {
  return `<div class="concept concept-17"><div class="cg-shell">
    <header class="cg-header"><a class="cg-brand" href="#cg-home" aria-label="XiuYu Zhang home">XZ<span>✦</span></a><span class="cg-location">COMPUTER SCIENCE / NUS</span><nav aria-label="Page navigation"><a href="#cg-about">About</a><a href="#cg-research">Research</a><a href="mailto:${esc(data.email)}">Contact ${arrow}</a></nav></header>
    <div><section id="cg-home" class="cg-hero" aria-labelledby="cg-name"><div class="cg-hero-label"><span>PERSONAL ACADEMIC PAGE</span><span>SINGAPORE</span></div><h1 id="cg-name">${esc(data.name)}<span class="cg-name-dot">.</span></h1><div class="cg-hero-bottom"><p>${esc(data.role)}<br>${esc(data.institution)}</p><nav aria-label="Profile links">${profiles(data)}</nav></div><div class="cg-motifs">${['Representation', 'Reasoning', 'Safety'].map((title, index) => `<div><span class="cg-motif-number">0${index + 1}</span>${motif(index)}<span class="cg-motif-title">${title}</span></div>`).join('')}</div></section>
    <section id="cg-about" class="cg-about" aria-labelledby="cg-about-title"><div class="cg-section-label"><span>01 / INTRODUCTION</span><h2 id="cg-about-title">A little about me.</h2></div><div class="full-introduction cg-introduction">${data.introductionHtml}</div><div class="cg-affiliations" aria-label="Research affiliations"><span>RESEARCH COMMUNITIES</span>${(data.groups || []).map(group => link(group.url, `${esc(group.name)} ${arrow}`)).join('')}</div></section>
    <section id="cg-research" class="cg-research" aria-labelledby="cg-research-title"><div class="cg-research-heading"><div><span class="cg-kicker">02 / SELECTED WORK</span><h2 id="cg-research-title">Ideas in<br><span>progress.</span></h2></div>${link(data.scholarUrl, `All publications ${arrow}`, 'cg-all-papers')}</div><div class="cg-paper-grid">${papers(data).map((paper, index) => `<article class="cg-paper"><div class="cg-paper-topline"><span>0${index + 1}</span><span>${esc(paper.tag)} / ${esc(paper.year)}</span></div>${link(paper.url, figure(paper), 'cg-figure')}<div class="cg-paper-body"><h3>${link(paper.url, esc(paper.title))}</h3><p class="cg-authors">${esc(paper.authors)}</p><nav class="cg-paper-links" aria-label="Resources for paper ${index + 1}">${paperLinks(paper)}</nav></div></article>`).join('')}</div></section></div>
    <footer class="cg-footer"><div><span class="cg-kicker">LET’S CONNECT</span><a class="cg-email" href="mailto:${esc(data.email)}">Say hello ${arrow}</a></div><div><span>${esc(data.name)}</span><a href="#cg-home">Back to top ↑</a></div></footer>
  </div></div>`;
}

function afterHours(data) {
  const orbit = '<svg class="ah-orbits" viewBox="0 0 1200 620" fill="none" aria-hidden="true"><g stroke="currentColor"><ellipse cx="600" cy="310" rx="555" ry="212" transform="rotate(-12 600 310)"/><ellipse cx="600" cy="310" rx="445" ry="290" transform="rotate(17 600 310)"/><ellipse cx="600" cy="310" rx="565" ry="125" transform="rotate(22 600 310)"/><ellipse cx="600" cy="310" rx="200" ry="305" transform="rotate(40 600 310)"/></g><g fill="currentColor"><circle cx="79" cy="219" r="5"/><circle cx="953" cy="475" r="7"/><circle cx="899" cy="119" r="4"/><circle cx="416" cy="560" r="3"/></g></svg>';
  return `<div class="concept concept-18"><div class="ah-shell"><header class="ah-header"><a href="#ah-home" class="ah-brand">XZ<span> / </span>RESEARCH</a><nav aria-label="Page navigation"><a href="#ah-about">About</a><a href="#ah-research">Publications</a><a href="mailto:${esc(data.email)}">Contact ${arrow}</a></nav></header>
    <div><section id="ah-home" class="ah-hero" aria-labelledby="ah-name">${orbit}<div class="ah-hero-content"><p class="ah-kicker">${esc(data.institution)}</p><h1 id="ah-name">${esc(data.name)}</h1><p class="ah-hero-thought">Understanding intelligence.<br><em>Building trust.</em></p><p class="ah-role">${esc(data.role)}</p><nav aria-label="Profile links">${profiles(data)}</nav></div><a href="#ah-about" class="ah-scroll"><span>KEEP EXPLORING</span><span aria-hidden="true">↓</span></a></section>
    <section id="ah-about" class="ah-about" aria-labelledby="ah-about-title"><div class="ah-about-heading"><span class="ah-kicker">01 / ABOUT ME</span><h2 id="ah-about-title">Questions worth<br><em>staying curious about.</em></h2></div><div class="full-introduction ah-introduction">${data.introductionHtml}</div></section>
    <section id="ah-research" class="ah-research" aria-labelledby="ah-research-title"><div class="ah-research-heading"><div><span class="ah-kicker">02 / PUBLICATIONS</span><h2 id="ah-research-title">Recent explorations<span>.</span></h2></div>${link(data.scholarUrl, `All publications ${arrow}`, 'ah-all-papers')}</div><div class="ah-papers">${papers(data).map((paper, index) => `<article class="ah-paper">${link(paper.url, `<span class="ah-figure-index">FIG. 0${index + 1}</span>${figure(paper)}`, 'ah-figure')}<div class="ah-paper-body"><p class="ah-paper-meta">${esc(paper.tag)} <span>·</span> ${esc(paper.year)}</p><h3>${link(paper.url, esc(paper.title))}</h3><p class="ah-authors">${esc(paper.authors)}</p><nav class="ah-paper-links" aria-label="Resources for paper ${index + 1}">${paperLinks(paper)}</nav></div></article>`).join('')}</div></section></div>
    <footer class="ah-footer"><p>Good ideas begin<br>with a <em>conversation.</em></p><a href="mailto:${esc(data.email)}">${esc(data.email)} ${arrow}</a><div><span>${esc(data.name)} · Singapore</span><a href="#ah-home">Back to top ↑</a></div></footer>
  </div></div>`;
}

export const concepts = { '17': { render: cobalt }, '18': { render: afterHours } };
