const e = (v = '') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const outer = (url, text, cls = '') => `<a class="${cls}" href="${e(url)}" target="_blank" rel="noopener noreferrer">${text}</a>`;
function circuit(data) {
  const drawing = `<svg class="oc-orbit" viewBox="0 0 600 540" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="1">${Array.from({length:14},(_,i)=>`<ellipse cx="300" cy="270" rx="${90+i*10}" ry="220" transform="rotate(${i*13} 300 270)"/>`).join('')}</g><circle cx="466" cy="135" r="12" fill="currentColor"/></svg>`;
  return `<div class="concept concept-20" id="oc-top"><header class="oc-nav"><a class="oc-logo" href="#oc-top" aria-label="XiuYu Zhang home">xz<span>↗</span></a><nav aria-label="Page navigation"><a href="#oc-about">About</a><a href="#oc-research">Research</a><a href="mailto:${e(data.email)}">Get in touch ↗</a></nav></header>
    <section class="oc-hero"><div class="oc-hero-top"><span>COMPUTER SCIENCE / NUS</span><span>SINGAPORE</span></div>${drawing}<div class="oc-name"><h1>XiuYu<br><em>Zhang.</em></h1><div class="oc-hero-note"><p>Reasoning.<br> Representation.<br> Reliable AI.</p><a href="#oc-about" aria-label="Read the full introduction">↓</a></div></div><div class="oc-hero-bottom"><span>${e(data.role)}</span>${outer(data.scholarUrl,'Google Scholar ↗')}</div></section>
    <div class="oc-wrap"><section class="oc-about" id="oc-about"><div class="oc-heading"><span class="oc-kicker">01 / INTRODUCTION</span><h2>Ideas into <br><em>intelligence.</em></h2></div><div class="oc-introduction full-introduction">${data.introductionHtml}</div></section>
    <section class="oc-research" id="oc-research"><div class="oc-research-heading"><div><span class="oc-kicker">02 / SELECTED WORK</span><h2>A closer look.</h2></div>${outer(data.scholarUrl,'All publications <span>↗</span>','oc-all')}</div><div class="oc-paper-grid">${data.papers.slice(0,4).map((p,i)=>`<article class="oc-paper"><div class="oc-paper-top"><span>0${i+1}</span><span>${e(p.tag)} / ${e(p.year)}</span></div>${outer(p.url,`<img src="${e(p.image)}" alt="Research figure from ${e(p.title)}" loading="lazy"><span class="oc-figure-arrow" aria-hidden="true">↗</span>`,'oc-figure')}<div class="oc-paper-copy"><h3>${outer(p.url,e(p.title))}</h3><p class="oc-authors">${e(p.authors).replaceAll('XiuYu Zhang','<strong>XiuYu Zhang</strong>')}</p><p class="oc-summary">${e(p.summary)}</p><div class="oc-paper-links">${outer(p.url,'Read paper ↗')}${p.code?outer(p.code,'Code ↗'):''}</div></div></article>`).join('')}</div></section>
    <section class="oc-background"><div class="oc-heading"><span class="oc-kicker">03 / BACKGROUND</span><h2>The path here.</h2></div><div class="oc-schools">${data.education.map(s=>`<article><span>${e(s.years)}</span><h3>${e(s.school)}</h3><p>${e(s.degree)}</p></article>`).join('')}</div></section>
    </div><footer class="oc-footer"><div class="oc-footer-top"><span class="oc-kicker">LET’S TALK RESEARCH.</span><a href="mailto:${e(data.email)}">Say hello. <span>↗</span></a></div><div class="oc-footer-bottom"><span>${e(data.name)} / ${e(data.institution)}</span><div>${outer(data.scholarUrl,'Scholar ↗')}${outer(data.githubUrl,'GitHub ↗')}<a href="#oc-top">Back to top ↑</a></div></div></footer></div>`;
}
export const concepts = {'20':{render:circuit}};
