const escape = (value = '') => String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
const arrow = '<span aria-hidden="true">↗</span>';
const label = (paper) => escape(paper.venue || paper.tag || 'Research');
const paperLink = (paper, text, className = '') => `<a class="${className}" href="${escape(paper.url)}" target="_blank" rel="noopener noreferrer">${text}</a>`;
const education = (data) => (data.education || []).map((item) => `<div><h3>${escape(item.school)}</h3><p>${escape(item.degree)}</p>${item.years ? `<span>${escape(item.years)}</span>` : ''}</div>`).join('');
const profileLinks = (data) => `<a href="${escape(data.scholarUrl)}" target="_blank" rel="noopener noreferrer">Google Scholar ${arrow}</a><a href="${escape(data.githubUrl)}" target="_blank" rel="noopener noreferrer">GitHub ${arrow}</a><a href="mailto:${escape(data.email)}">Email ${arrow}</a>`;

function editorial(data) {
  const papers = data.papers.slice(0, 5);
  return `<div class="concept concept-01">
    <div class="ed-wrap">
      <header class="ed-masthead"><a href="#ed-top" class="ed-wordmark">XZ<span> / </span>RESEARCH</a><span class="ed-masthead-place">${escape(data.institution)}<br>${escape(data.lab)}</span><a href="mailto:${escape(data.email)}">Get in touch ${arrow}</a></header>
      <main id="ed-top">
        <section class="ed-hero" aria-labelledby="ed-name"><div class="ed-kicker"><span>COMPUTER SCIENCE</span><span>SINGAPORE · NUS</span></div><h1 id="ed-name">XiuYu <em>Zhang.</em></h1><div class="ed-intro"><p class="ed-role">${escape(data.role)}<span>${escape(data.institution)}</span></p><p class="ed-bio">${escape(data.bio)}</p></div><div class="ed-hero-bottom"><a href="#ed-research">Explore my research <span aria-hidden="true">↓</span></a><span class="ed-tiny">LANGUAGE / VISION / INTELLIGENCE</span></div></section>
        <section class="ed-research" id="ed-research" aria-labelledby="ed-research-title"><div class="ed-section-label"><span>01 / RESEARCH</span><span>SELECTED WORK</span></div><div class="ed-research-grid"><aside class="ed-research-intro"><h2 id="ed-research-title">Ideas into<br> <em>evidence.</em></h2><p>Selected papers exploring intelligence, learning, and the systems around them.</p><div class="ed-topics">${data.interests.map((interest, i) => `<span><small>0${i + 1}</small>${escape(interest)}</span>`).join('')}</div><a class="ed-scholar" href="${escape(data.scholarUrl)}" target="_blank" rel="noopener noreferrer">Complete publication list ${arrow}</a></aside><div class="ed-paper-list">${papers.map((paper, i) => `<article class="ed-paper"><span class="ed-paper-number">0${i + 1}</span><div><div class="ed-paper-meta"><span>${label(paper)}</span><time>${escape(paper.year)}</time></div><h3>${paperLink(paper, `${escape(paper.title)} ${arrow}`)}</h3><p>${escape(paper.authors)}</p></div></article>`).join('')}</div></div></section>
        <section class="ed-background" aria-labelledby="ed-background-title"><div class="ed-section-label"><span>02 / BACKGROUND</span><span>A CONTINUING JOURNEY</span></div><h2 id="ed-background-title">Learning, <em>always.</em></h2><div class="ed-education">${education(data)}</div></section>
      </main><footer class="ed-footer"><div><span>LET'S CONNECT</span><a class="ed-email" href="mailto:${escape(data.email)}">${escape(data.email)} ${arrow}</a></div><nav aria-label="Profile links">${profileLinks(data)}</nav><span class="ed-footer-note">${escape(data.name)} · ${escape(data.institution)}</span></footer>
    </div>
  </div>`;
}

function swiss(data) {
  const papers = data.papers.slice(0, 5);
  return `<div class="concept concept-02">
    <header class="sw-header"><a class="sw-brand" href="#sw-top">XZ<span>↗</span></a><span>ACADEMIC PROFILE<br>COMPUTER SCIENCE</span><nav aria-label="Page navigation"><a href="#sw-work">Research <span>01</span></a><a href="#sw-about">About <span>02</span></a><a href="mailto:${escape(data.email)}">Contact ${arrow}</a></nav></header>
    <main id="sw-top"><section class="sw-hero" aria-labelledby="sw-name"><div class="sw-hero-content"><span class="sw-eyebrow">${escape(data.institution)}</span><h1 id="sw-name">XiuYu<br>Zhang<span class="sw-name-dot">.</span></h1><div class="sw-hero-footer"><p>${escape(data.role)}<br>${escape(data.lab)}</p><a href="#sw-work" aria-label="Explore research">↓</a></div></div><div class="sw-graphic" aria-hidden="true"><span class="sw-graphic-label">FORM / STRUCTURE / INTELLIGENCE</span><div class="sw-graphic-grid"><span></span><span></span><span></span><span></span></div><span class="sw-graphic-coordinate">01 — ∞<br>RESEARCH IN PROGRESS</span></div></section>
    <section class="sw-overview" id="sw-about"><div class="sw-index"><span>01—</span><h2>Perspective</h2></div><div><p class="sw-bio">${escape(data.bio)}</p><div class="sw-interests">${data.interests.map((interest) => `<span>${escape(interest)}</span>`).join('')}</div></div></section>
    <section class="sw-work" id="sw-work" aria-labelledby="sw-work-title"><div class="sw-work-heading"><div><span class="sw-eyebrow">RESEARCH INDEX</span><h2 id="sw-work-title">Selected work<span> (${String(papers.length).padStart(2, '0')})</span></h2></div><a href="${escape(data.scholarUrl)}" target="_blank" rel="noopener noreferrer">Full bibliography ${arrow}</a></div><div class="sw-papers">${papers.map((paper, i) => `<article class="sw-paper"><div class="sw-paper-index"><span>${String(i + 1).padStart(2, '0')}</span><time>${escape(paper.year)}</time></div><div class="sw-paper-body"><span class="sw-venue">${label(paper)}</span><h3>${paperLink(paper, escape(paper.title))}</h3><p>${escape(paper.authors)}</p></div>${paperLink(paper, arrow, 'sw-paper-arrow')}</article>`).join('')}</div></section>
    <section class="sw-education"><div class="sw-index"><span>02—</span><h2>Education</h2></div><div class="sw-education-list">${education(data)}</div></section>
    </main><footer class="sw-footer"><span class="sw-footer-name">Let's exchange<br><span>ideas.</span></span><div class="sw-footer-right"><a class="sw-email" href="mailto:${escape(data.email)}">${escape(data.email)} ${arrow}</a><nav aria-label="Profile links">${profileLinks(data)}</nav><small>${escape(data.name)} / Singapore</small></div></footer>
  </div>`;
}

function quiet(data) {
  return `<div class="concept concept-03"><div class="qs-layout"><aside class="qs-sidebar"><a class="qs-monogram" href="#qs-top" aria-label="XiuYu Zhang home">xz<span>.</span></a><h1>${escape(data.name)}</h1><p class="qs-role">${escape(data.role)}</p><p class="qs-affiliation">${escape(data.institution)}<br>${escape(data.lab)}</p><div class="qs-sidebar-rule"></div><nav class="qs-page-nav" aria-label="Page navigation"><a href="#qs-about"><span>01</span> About</a><a href="#qs-research"><span>02</span> Research</a><a href="#qs-education"><span>03</span> Education</a></nav><nav class="qs-social" aria-label="Profile links">${profileLinks(data)}</nav><span class="qs-location"><span aria-hidden="true">⊙</span> Based in Singapore</span></aside>
    <main id="qs-top"><section class="qs-intro" id="qs-about"><span class="qs-overline">A SPACE FOR IDEAS & INQUIRY</span><h2>Understanding<br>intelligence.<br><em>Building thoughtfully.</em></h2><div class="qs-ornament" aria-hidden="true">✳</div><p class="qs-bio">${escape(data.bio)}</p><div class="qs-interests"><span class="qs-small-label">RESEARCH INTERESTS</span><p>${data.interests.map(escape).join('<span aria-hidden="true"> · </span>')}</p></div></section>
    <section class="qs-research" id="qs-research" aria-labelledby="qs-research-title"><div class="qs-section-heading"><h2 id="qs-research-title">Selected research</h2><span>02 /</span></div><p class="qs-section-note">Papers, questions, and work in progress.</p><div class="qs-papers">${data.papers.slice(0, 5).map((paper) => `<article class="qs-paper"><div class="qs-paper-meta"><span>${label(paper)}</span><time>${escape(paper.year)}</time></div><h3>${paperLink(paper, escape(paper.title))}</h3><p>${escape(paper.authors)}</p>${paperLink(paper, `Read paper ${arrow}`, 'qs-read-paper')}</article>`).join('')}</div><a class="qs-all-papers" href="${escape(data.scholarUrl)}" target="_blank" rel="noopener noreferrer">All publications on Google Scholar ${arrow}</a></section>
    <section class="qs-education" id="qs-education" aria-labelledby="qs-education-title"><div class="qs-section-heading"><h2 id="qs-education-title">Education</h2><span>03 /</span></div><div class="qs-education-list">${education(data)}</div></section>
    <footer class="qs-footer"><span>Conversations begin with a hello.</span><a href="mailto:${escape(data.email)}">${escape(data.email)} ${arrow}</a><small>${escape(data.name)} · ${escape(data.institution)}</small></footer></main></div></div>`;
}

export const concepts = { '01': { render: editorial }, '02': { render: swiss }, '03': { render: quiet } };
