const escape = (value = '') => String(value).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link = (url, text, cls = '', label = '') => `<a class="${cls}" href="${escape(url)}" target="_blank" rel="noopener noreferrer"${label ? ` aria-label="${escape(label)}"` : ''}>${text}</a>`;
const short = (text, max = 175) => text && text.length > max ? `${text.slice(0, max).replace(/\s+\S*$/, '')}…` : text || '';
const footer = (d, cls) => `<footer class="${cls}-footer"><div><span class="${cls}-eyebrow">LET’S CONNECT</span><a class="${cls}-email" href="mailto:${escape(d.email)}">${escape(d.email)} <span aria-hidden="true">↗</span></a></div><div class="${cls}-footer-links">${link(d.scholarUrl, 'Google Scholar ↗')}${link(d.githubUrl, 'GitHub ↗')}</div></footer>`;

function gallery(d) {
  const projects = d.papers.slice(0, 4);
  return `<div class="concept concept-07">
    <div class="g07-shell">
      <header class="g07-header"><a class="g07-wordmark" href="#g07-home">${escape(d.name)}<span>RESEARCH & EXPLORATIONS</span></a><nav aria-label="Concept navigation"><a href="#g07-work">Selected work</a><a href="#g07-about">About</a><a href="mailto:${escape(d.email)}">Contact ↗</a></nav></header>
      <main id="g07-home">
        <section class="g07-hero"><div class="g07-hero-label"><span class="g07-small-dot"></span> ${escape(d.institution)}<br><span>${escape(d.role)}</span></div><h1>Intelligence,<br>with <em>intention.</em></h1><div class="g07-intro"><span class="g07-asterisk" aria-hidden="true">✳</span><p>${escape(short(d.bio, 240))}</p><a href="#g07-work" class="g07-round" aria-label="Explore selected work">↓</a></div></section>
        <section id="g07-work" class="g07-work"><div class="g07-section-head"><h2>Selected explorations</h2><span>01 — ${String(projects.length).padStart(2, '0')}</span></div><div class="g07-grid">${projects.map((p,i) => `<article class="g07-project g07-project-${i}"><a class="g07-figure" href="${escape(p.url)}" target="_blank" rel="noopener noreferrer">${p.image ? `<img src="${escape(p.image)}" alt="Research figure from ${escape(p.title)}" loading="lazy">` : `<span class="g07-figure-fallback">${escape(p.tag || 'Research')}<span>↗</span></span>`}<span class="g07-open" aria-hidden="true">↗</span></a><div class="g07-project-meta"><span>0${i+1} / ${escape(p.tag || 'Research')}</span><span>${escape(p.year)}</span></div><h3>${link(p.url, escape(p.title))}</h3><p>${escape(short(p.summary, 140))}</p><span class="g07-venue">${escape(p.venue)}</span></article>`).join('')}</div></section>
        <section class="g07-about" id="g07-about"><div><span class="g07-eyebrow">BEHIND THE RESEARCH</span><h2>Curiosity is<br>the starting point.</h2></div><div><p>${escape(d.bio)}</p><div class="g07-interests">${d.interests.map(x => `<span>${escape(x)}</span>`).join('')}</div><a href="${escape(d.scholarUrl)}" target="_blank" rel="noopener noreferrer" class="g07-text-link">Explore all publications <span>↗</span></a></div></section>
      </main>${footer(d, 'g07')}
    </div>
  </div>`;
}

function atlas(d) {
  const graph = `<svg viewBox="0 0 620 290" role="img" aria-label="Conceptual research map connecting language models with reasoning, safety, and multimodal learning"><defs><pattern id="a08-grid" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".85" fill="#d9e3ee"/></pattern></defs><rect width="620" height="290" fill="url(#a08-grid)"/><g fill="none" stroke="#a6bce0" stroke-width="1.5"><path d="M306 144C250 144 212 71 145 71M306 144C385 144 383 65 475 65M306 144C280 204 210 226 155 226M306 144C348 217 403 219 473 219"/><path stroke-dasharray="3 5" d="M145 71Q83 151 155 226M475 65Q551 142 473 219M145 71Q303 -7 475 65M155 226Q316 281 473 219"/></g><g fill="#fff" stroke="#c4d3e6"><rect x="40" y="48" width="181" height="46" rx="5"/><rect x="400" y="42" width="175" height="46" rx="5"/><rect x="55" y="203" width="199" height="46" rx="5"/><rect x="390" y="196" width="187" height="46" rx="5"/></g><circle cx="306" cy="144" r="51" fill="#edf3ff" stroke="#bdcff3"/><circle cx="306" cy="144" r="39" fill="#2459d4"/><g font-family="DM Sans, sans-serif" text-anchor="middle" font-size="13" fill="#345170"><text x="130" y="76">Reasoning & evaluation</text><text x="488" y="70">Safety & alignment</text><text x="155" y="231">Multimodal learning</text><text x="484" y="224">Security & systems</text></g><g font-family="DM Sans, sans-serif" text-anchor="middle" font-size="12" fill="white"><text x="306" y="141">Language</text><text x="306" y="157">models</text></g><g fill="#2459d4"><circle cx="214" cy="105" r="3"/><circle cx="389" cy="113" r="3"/><circle cx="244" cy="209" r="3"/><circle cx="374" cy="205" r="3"/></g></svg>`;
  return `<div class="concept concept-08"><div class="a08-layout">
    <aside class="a08-rail"><a class="a08-symbol" href="#a08-overview" aria-label="XiuYu Zhang overview">xz<span>↗</span></a><div class="a08-identity"><h2>${escape(d.name)}</h2><p>${escape(d.role)}</p><p>${escape(d.institution)}</p></div><div class="a08-rail-label">EXPLORE</div><nav aria-label="Concept navigation"><a href="#a08-overview"><span>01</span> Overview</a><a href="#a08-research"><span>02</span> Research</a><a href="#a08-background"><span>03</span> Background</a><a href="#a08-contact"><span>04</span> Contact</a></nav><div class="a08-rail-bottom"><span class="a08-rail-label">ELSEWHERE</span>${link(d.scholarUrl, 'Google Scholar ↗')}${link(d.githubUrl, 'GitHub ↗')}<a href="mailto:${escape(d.email)}">Email ↗</a></div></aside>
    <div class="a08-main"><header class="a08-header"><span>PERSONAL RESEARCH ATLAS</span><span>Singapore · NUS</span></header><main>
      <section class="a08-overview" id="a08-overview"><div class="a08-section-marker"><span>01</span> OVERVIEW</div><h1>A closer look at<br><em>intelligent systems.</em></h1><p class="a08-lead">${escape(d.bio)}</p><div class="a08-map"><div class="a08-map-head"><span><i></i> RESEARCH LANDSCAPE</span><span>CONCEPTUAL MAP</span></div>${graph}<div class="a08-map-foot">Connected questions. Shared foundations.</div></div><div class="a08-topics">${d.interests.map((x,i) => `<span><b>${String(i+1).padStart(2,'0')}</b>${escape(x)}</span>`).join('')}</div></section>
      <section id="a08-research" class="a08-research"><div class="a08-section-marker"><span>02</span> RESEARCH</div><div class="a08-title-row"><h2>Publication index</h2>${link(d.scholarUrl, 'Full bibliography ↗')}</div><div class="a08-table-head"><span>YEAR</span><span>TITLE / CONTRIBUTORS</span><span>VENUE</span><span></span></div><div class="a08-papers">${d.papers.slice(0,6).map(p=>`<article class="a08-paper"><div class="a08-year">${escape(p.year)}</div><div><h3>${link(p.url,escape(p.title))}</h3><p>${escape(short(p.authors,120))}</p></div><div class="a08-venue" title="${escape(p.venue)}">${escape(p.tag || p.venue)}</div>${link(p.url, '↗', 'a08-arrow', `Read ${p.title}`)}</article>`).join('')}</div></section>
      <section id="a08-background" class="a08-background"><div class="a08-section-marker"><span>03</span> BACKGROUND</div><h2>Learning, in context.</h2><div class="a08-background-grid"><div><span class="a08-detail-label">CURRENT AFFILIATION</span><h3>${escape(d.institution)}</h3><p>${escape(d.lab)}</p><p>${escape(d.role)}</p></div><div><span class="a08-detail-label">EDUCATION</span>${d.education.map(e=>`<div class="a08-education"><h3>${escape(e.school)}</h3><p>${escape(e.degree)}</p>${e.years ? `<span>${escape(e.years)}</span>` : ''}</div>`).join('')}</div></div></section>
      <section id="a08-contact" class="a08-contact"><div><div class="a08-section-marker"><span>04</span> CONTACT</div><h2>Continue the conversation.</h2></div><a href="mailto:${escape(d.email)}">${escape(d.email)} <span>↗</span></a></section>
    </main><footer class="a08-footer"><span>${escape(d.name)} · Academic portfolio</span><a href="#a08-overview">Back to overview ↑</a></footer></div>
  </div></div>`;
}

function studio(d) {
  return `<div class="concept concept-09"><div class="m09-shell">
    <header class="m09-header"><a href="#m09-home" class="m09-wordmark">XZ<span>↗</span></a><span class="m09-header-label">${escape(d.name)}<br>COMPUTER SCIENCE RESEARCHER</span><nav aria-label="Concept navigation"><a href="#m09-work">Work [01]</a><a href="#m09-about">About [02]</a><a href="mailto:${escape(d.email)}">Contact ↗</a></nav></header>
    <main><section id="m09-home" class="m09-hero"><div class="m09-kicker"><span>RESEARCH PORTFOLIO</span><span>${escape(d.institution)} ↗</span></div><h1>THINK<br><span>DEEPER.</span></h1><div class="m09-hero-bottom"><div class="m09-orbit" aria-hidden="true"><svg viewBox="0 0 150 100"><g fill="none" stroke="currentColor" stroke-width="1.3"><ellipse cx="75" cy="50" rx="66" ry="31"/><ellipse cx="75" cy="50" rx="66" ry="31" transform="rotate(35 75 50)"/><ellipse cx="75" cy="50" rx="66" ry="31" transform="rotate(-35 75 50)"/><ellipse cx="75" cy="50" rx="25" ry="46"/></g></svg></div><p>${escape(short(d.bio,215))}</p><a href="#m09-work" aria-label="View research" class="m09-down">↙</a></div></section>
      <section class="m09-work" id="m09-work"><div class="m09-section-line"><h2>SELECTED WORK</h2><span>RESEARCH / PUBLICATIONS</span></div>${d.papers.slice(0,5).map((p,i)=>`<article class="m09-paper"><span class="m09-number">(0${i+1})</span><div class="m09-paper-main"><div class="m09-paper-meta"><span>${escape(p.venue || p.tag)}</span><span>${escape(p.year)}</span></div><h3>${link(p.url,escape(p.title))}</h3><p>${escape(short(p.summary,140))}</p></div>${link(p.url,'↗','m09-paper-arrow', `Read ${p.title}`)}</article>`).join('')}<a href="${escape(d.scholarUrl)}" class="m09-all" target="_blank" rel="noopener noreferrer">ALL PUBLICATIONS <span>↗</span></a></section>
      <section class="m09-about" id="m09-about"><span class="m09-about-label">(ABOUT)</span><div><h2>Good research<br>starts with<br><span>better questions.</span></h2><div class="m09-about-copy"><p>${escape(d.bio)}</p><div class="m09-interests">${d.interests.map(x=>`<span>${escape(x)}</span>`).join('')}</div></div></div></section>
    </main><footer class="m09-footer"><span>HAVE A QUESTION?</span><a href="mailto:${escape(d.email)}" class="m09-talk">LET’S TALK<span>↗</span></a><div class="m09-footer-bottom"><span>${escape(d.name)} / ${escape(d.institution)}</span><div>${link(d.scholarUrl,'GOOGLE SCHOLAR ↗')}${link(d.githubUrl,'GITHUB ↗')}</div></div></footer>
  </div></div>`;
}

export const concepts = {'07': {render: gallery}, '08': {render: atlas}, '09': {render: studio}};
